name: Deploy Portfolio via SSH

on:
  push:
    branches: [ "main" ]   # ganti kalau branch-mu beda
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-portfolio
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create remote dir (first time safe)
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "mkdir -p '${{ secrets.REMOTE_PATH }}'"

      - name: Rsync dist -> server
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SSH_PORT }}" \
            dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/yogasungkowo/Project/webdev_portfolio/dist/


      # (Opsional) Reload Nginx kalau kamu ingin pasti refresh log/permision
      # - name: Reload Nginx
      #   run: |
      #     ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SSH_PORT }} \
      #       ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
      #       "sudo nginx -t && sudo systemctl reload nginx"
